import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

import type { Project } from "@/lib/projects";
import type { JobMaterial } from "@/lib/jobMaterials";
import type { JobPhoto } from "@/lib/jobPhotos";
import type { DailyNote } from "@/lib/dailyNotes";

import {
  calculateTimeEntryHours,
  type TimeEntry,
} from "@/lib/timeEntries";

export type ProjectReportData = {
  project: Project;
  timeEntries: TimeEntry[];
  materials: JobMaterial[];
  photos: JobPhoto[];
  dailyNotes: DailyNote[];
};

type EmployeeLaborRow = {
  employeeName: string;
  hours: number;
};

const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const LEFT_MARGIN = 15;
const RIGHT_MARGIN = 15;
const CONTENT_WIDTH =
  PAGE_WIDTH - LEFT_MARGIN - RIGHT_MARGIN;

function formatDate(dateValue?: string | null) {
  if (!dateValue) {
    return "Not set";
  }

  const date = new Date(dateValue);

  if (Number.isNaN(date.getTime())) {
    return dateValue;
  }

  return date.toLocaleDateString([], {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

function formatDateTime(dateValue: string) {
  const date = new Date(dateValue);

  if (Number.isNaN(date.getTime())) {
    return "Date unavailable";
  }

  return date.toLocaleString([], {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

function formatQuantity(quantity: number) {
  return Number.isInteger(quantity)
    ? String(quantity)
    : quantity.toFixed(2);
}

function sanitizeFileName(value: string) {
  return value
    .trim()
    .replace(/[<>:"/\\|?*]+/g, "")
    .replace(/\s+/g, "-")
    .toLowerCase();
}

function getLaborRows(
  entries: TimeEntry[]
): EmployeeLaborRow[] {
  const employeeTotals = new Map<
    string,
    number
  >();

  entries.forEach((entry) => {
    const currentHours =
      employeeTotals.get(
        entry.employeeName
      ) ?? 0;

    employeeTotals.set(
      entry.employeeName,
      currentHours +
        calculateTimeEntryHours(entry)
    );
  });

  return Array.from(
    employeeTotals.entries()
  )
    .map(
      ([employeeName, hours]) => ({
        employeeName,
        hours,
      })
    )
    .sort(
      (firstEmployee, secondEmployee) =>
        secondEmployee.hours -
        firstEmployee.hours
    );
}

function getTotalLaborHours(
  entries: TimeEntry[]
) {
  return entries.reduce(
    (total, entry) =>
      total +
      calculateTimeEntryHours(entry),
    0
  );
}

function addReportHeader(
  doc: jsPDF,
  project: Project
) {
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, PAGE_WIDTH, 32, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("JobClokr", LEFT_MARGIN, 14);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(
    "Project Report",
    LEFT_MARGIN,
    22
  );

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);

  const projectName = doc.splitTextToSize(
    project.name,
    80
  );

  doc.text(
    projectName,
    PAGE_WIDTH - RIGHT_MARGIN,
    13,
    {
      align: "right",
    }
  );

  doc.setTextColor(15, 23, 42);
}

function addPageFooter(
  doc: jsPDF,
  pageNumber: number,
  totalPages: number
) {
  doc.setDrawColor(226, 232, 240);

  doc.line(
    LEFT_MARGIN,
    PAGE_HEIGHT - 15,
    PAGE_WIDTH - RIGHT_MARGIN,
    PAGE_HEIGHT - 15
  );

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);

  doc.text(
    "Generated by JobClokr",
    LEFT_MARGIN,
    PAGE_HEIGHT - 9
  );

  doc.text(
    `Page ${pageNumber} of ${totalPages}`,
    PAGE_WIDTH - RIGHT_MARGIN,
    PAGE_HEIGHT - 9,
    {
      align: "right",
    }
  );

  doc.setTextColor(15, 23, 42);
}

function addSectionHeading(
  doc: jsPDF,
  title: string,
  yPosition: number
) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);

  doc.text(title, LEFT_MARGIN, yPosition);

  doc.setDrawColor(37, 99, 235);
  doc.setLineWidth(0.8);

  doc.line(
    LEFT_MARGIN,
    yPosition + 3,
    PAGE_WIDTH - RIGHT_MARGIN,
    yPosition + 3
  );

  return yPosition + 10;
}

function ensurePageSpace(
  doc: jsPDF,
  yPosition: number,
  requiredHeight: number,
  project: Project
) {
  if (
    yPosition + requiredHeight <=
    PAGE_HEIGHT - 22
  ) {
    return yPosition;
  }

  doc.addPage();
  addReportHeader(doc, project);

  return 43;
}

function getImageFormat(
  imageData: string
): "PNG" | "JPEG" | "WEBP" {
  const normalized =
    imageData.toLowerCase();

  if (
    normalized.startsWith(
      "data:image/png"
    )
  ) {
    return "PNG";
  }

  if (
    normalized.startsWith(
      "data:image/webp"
    )
  ) {
    return "WEBP";
  }

  return "JPEG";
}

function addPhotoGallery(
  doc: jsPDF,
  project: Project,
  photos: JobPhoto[],
  startingY: number
) {
  let yPosition = startingY;

  if (photos.length === 0) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);

    doc.text(
      "No job photos were recorded for this project.",
      LEFT_MARGIN,
      yPosition
    );

    doc.setTextColor(15, 23, 42);

    return yPosition + 8;
  }

  const photoWidth = 82;
  const photoHeight = 58;
  const columnGap = 12;
  const cardHeight = 78;

  photos.forEach((photo, index) => {
    const column = index % 2;

    if (
      column === 0 &&
      index > 0
    ) {
      yPosition += cardHeight;
    }

    yPosition = ensurePageSpace(
      doc,
      yPosition,
      cardHeight,
      project
    );

    const xPosition =
      LEFT_MARGIN +
      column *
        (photoWidth + columnGap);

    try {
      doc.addImage(
        photo.imageData,
        getImageFormat(photo.imageData),
        xPosition,
        yPosition,
        photoWidth,
        photoHeight,
        undefined,
        "FAST"
      );
    } catch {
      doc.setFillColor(241, 245, 249);

      doc.rect(
        xPosition,
        yPosition,
        photoWidth,
        photoHeight,
        "F"
      );

      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);

      doc.text(
        "Photo unavailable",
        xPosition + photoWidth / 2,
        yPosition + photoHeight / 2,
        {
          align: "center",
        }
      );
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(15, 23, 42);

    doc.text(
      photo.employeeName,
      xPosition,
      yPosition + photoHeight + 5
    );

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(100, 116, 139);

    doc.text(
      formatDateTime(photo.createdAt),
      xPosition,
      yPosition + photoHeight + 10
    );

    if (photo.note) {
      const noteLines =
        doc.splitTextToSize(
          photo.note,
          photoWidth
        );

      doc.text(
        noteLines.slice(0, 2),
        xPosition,
        yPosition + photoHeight + 15
      );
    }

    doc.setTextColor(15, 23, 42);
  });

  return (
    yPosition +
    cardHeight +
    (photos.length % 2 === 0
      ? 0
      : cardHeight)
  );
}

export function generateProjectReport({
  project,
  timeEntries,
  materials,
  photos,
  dailyNotes,
}: ProjectReportData) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const projectTimeEntries =
    timeEntries.filter(
      (entry) =>
        entry.projectId === project.id
    );

  const projectMaterials =
    materials.filter(
      (material) =>
        material.projectId === project.id
    );

  const projectPhotos =
    photos.filter(
      (photo) =>
        photo.projectId === project.id
    );

  const projectNotes =
    dailyNotes.filter(
      (note) =>
        note.projectId === project.id
    );

  const laborRows = getLaborRows(
    projectTimeEntries
  );

  const totalLaborHours =
    getTotalLaborHours(
      projectTimeEntries
    );

  addReportHeader(doc, project);

  let yPosition = 43;

  yPosition = addSectionHeading(
    doc,
    "Project Information",
    yPosition
  );

  autoTable(doc, {
    startY: yPosition,
    theme: "grid",

    head: [
      [
        "Field",
        "Project Information",
      ],
    ],

    body: [
      ["Project", project.name],
      ["Customer", project.customer],
      ["Status", project.status],
      [
        "Address",
        project.address ||
          "No address added",
      ],
      [
        "Start Date",
        formatDate(project.startDate),
      ],
      [
        "Due Date",
        formatDate(project.dueDate),
      ],
      [
        "Assigned Employees",
        String(
          project.employees.length
        ),
      ],
      [
        "Description",
        project.details ||
          "No project description added",
      ],
    ],

    margin: {
      left: LEFT_MARGIN,
      right: RIGHT_MARGIN,
    },

    styles: {
      fontSize: 9,
      cellPadding: 3,
      overflow: "linebreak",
    },

    headStyles: {
      fillColor: [37, 99, 235],
      textColor: [255, 255, 255],
    },

    columnStyles: {
      0: {
        cellWidth: 48,
        fontStyle: "bold",
      },

      1: {
        cellWidth: CONTENT_WIDTH - 48,
      },
    },
  });

  yPosition =
    (doc.lastAutoTable?.finalY ??
      yPosition) + 12;

  yPosition = ensurePageSpace(
    doc,
    yPosition,
    45,
    project
  );

  yPosition = addSectionHeading(
    doc,
    "Labor Summary",
    yPosition
  );

  autoTable(doc, {
    startY: yPosition,
    theme: "striped",

    head: [
      [
        "Employee",
        "Time Entries",
        "Hours",
      ],
    ],

    body:
      laborRows.length > 0
        ? laborRows.map((laborRow) => [
            laborRow.employeeName,

            String(
              projectTimeEntries.filter(
                (entry) =>
                  entry.employeeName ===
                  laborRow.employeeName
              ).length
            ),

            laborRow.hours.toFixed(2),
          ])
        : [
            [
              "No labor recorded",
              "0",
              "0.00",
            ],
          ],

    foot: [
      [
        "Project Total",
        String(
          projectTimeEntries.length
        ),
        totalLaborHours.toFixed(2),
      ],
    ],

    margin: {
      left: LEFT_MARGIN,
      right: RIGHT_MARGIN,
    },

    styles: {
      fontSize: 9,
      cellPadding: 3,
    },

    headStyles: {
      fillColor: [15, 23, 42],
      textColor: [255, 255, 255],
    },

    footStyles: {
      fillColor: [219, 234, 254],
      textColor: [30, 64, 175],
      fontStyle: "bold",
    },
  });

  yPosition =
    (doc.lastAutoTable?.finalY ??
      yPosition) + 12;

  yPosition = ensurePageSpace(
    doc,
    yPosition,
    45,
    project
  );

  yPosition = addSectionHeading(
    doc,
    "Materials Used",
    yPosition
  );

  autoTable(doc, {
    startY: yPosition,
    theme: "striped",

    head: [
      [
        "Material",
        "Quantity",
        "Employee",
        "Date",
        "Notes",
      ],
    ],

    body:
      projectMaterials.length > 0
        ? projectMaterials.map(
            (material) => [
              material.materialName,

              `${formatQuantity(
                material.quantity
              )} ${material.unit}`,

              material.employeeName,

              formatDateTime(
                material.createdAt
              ),

              material.notes ||
                "No notes",
            ]
          )
        : [
            [
              "No materials recorded",
              "",
              "",
              "",
              "",
            ],
          ],

    margin: {
      left: LEFT_MARGIN,
      right: RIGHT_MARGIN,
    },

    styles: {
      fontSize: 8,
      cellPadding: 2.5,
      overflow: "linebreak",
    },

    headStyles: {
      fillColor: [15, 23, 42],
      textColor: [255, 255, 255],
    },

    columnStyles: {
      0: {
        cellWidth: 38,
      },

      1: {
        cellWidth: 25,
      },

      2: {
        cellWidth: 32,
      },

      3: {
        cellWidth: 34,
      },

      4: {
        cellWidth: CONTENT_WIDTH - 129,
      },
    },
  });

  yPosition =
    (doc.lastAutoTable?.finalY ??
      yPosition) + 12;

  yPosition = ensurePageSpace(
    doc,
    yPosition,
    40,
    project
  );

  yPosition = addSectionHeading(
    doc,
    "Daily Notes",
    yPosition
  );

  if (projectNotes.length === 0) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);

    doc.text(
      "No daily notes were recorded for this project.",
      LEFT_MARGIN,
      yPosition
    );

    doc.setTextColor(15, 23, 42);
    yPosition += 10;
  } else {
    projectNotes.forEach(
      (note, index) => {
        const noteLines =
          doc.splitTextToSize(
            note.note,
            CONTENT_WIDTH - 10
          );

        const noteHeight =
          noteLines.length * 5 + 18;

        yPosition = ensurePageSpace(
          doc,
          yPosition,
          noteHeight,
          project
        );

        doc.setFillColor(248, 250, 252);

        doc.roundedRect(
          LEFT_MARGIN,
          yPosition,
          CONTENT_WIDTH,
          noteHeight,
          2,
          2,
          "F"
        );

        doc.setFont(
          "helvetica",
          "bold"
        );

        doc.setFontSize(9);
        doc.setTextColor(15, 23, 42);

        doc.text(
          note.employeeName,
          LEFT_MARGIN + 4,
          yPosition + 6
        );

        doc.setFont(
          "helvetica",
          "normal"
        );

        doc.setFontSize(8);
        doc.setTextColor(
          100,
          116,
          139
        );

        doc.text(
          formatDateTime(
            note.createdAt
          ),
          PAGE_WIDTH -
            RIGHT_MARGIN -
            4,
          yPosition + 6,
          {
            align: "right",
          }
        );

        doc.setFontSize(9);
        doc.setTextColor(51, 65, 85);

        doc.text(
          noteLines,
          LEFT_MARGIN + 4,
          yPosition + 13
        );

        yPosition +=
          noteHeight + 5;

        if (
          index <
          projectNotes.length - 1
        ) {
          yPosition += 1;
        }
      }
    );
  }

  yPosition = ensurePageSpace(
    doc,
    yPosition + 4,
    50,
    project
  );

  yPosition = addSectionHeading(
    doc,
    `Job Photos (${projectPhotos.length})`,
    yPosition + 4
  );

  addPhotoGallery(
    doc,
    project,
    projectPhotos,
    yPosition
  );

  const totalPages =
    doc.getNumberOfPages();

  for (
    let pageNumber = 1;
    pageNumber <= totalPages;
    pageNumber += 1
  ) {
    doc.setPage(pageNumber);

    addPageFooter(
      doc,
      pageNumber,
      totalPages
    );
  }

  const generatedDate =
    new Date()
      .toISOString()
      .slice(0, 10);

  const fileName =
    `${sanitizeFileName(
      project.name
    )}-project-report-${generatedDate}.pdf`;

  doc.save(fileName);
}