import type { jsPDF } from "jspdf";

export const PDF_PAGE_WIDTH = 210;
export const PDF_PAGE_HEIGHT = 297;

export const PDF_LEFT_MARGIN = 15;
export const PDF_RIGHT_MARGIN = 15;
export const PDF_TOP_MARGIN = 18;
export const PDF_BOTTOM_MARGIN = 18;

export const PDF_CONTENT_WIDTH =
  PDF_PAGE_WIDTH -
  PDF_LEFT_MARGIN -
  PDF_RIGHT_MARGIN;

export const PDF_COLORS = {
  primary: [37, 99, 235] as const,
  primaryDark: [30, 64, 175] as const,

  heading: [15, 23, 42] as const,
  body: [51, 65, 85] as const,
  muted: [100, 116, 139] as const,

  border: [226, 232, 240] as const,
  panel: [248, 250, 252] as const,

  success: [22, 163, 74] as const,
  warning: [217, 119, 6] as const,
  danger: [220, 38, 38] as const,

  white: [255, 255, 255] as const,
};

export function setPdfTextColor(
  doc: jsPDF,
  color: readonly [
    number,
    number,
    number,
  ]
) {
  doc.setTextColor(
    color[0],
    color[1],
    color[2]
  );
}

export function setPdfFillColor(
  doc: jsPDF,
  color: readonly [
    number,
    number,
    number,
  ]
) {
  doc.setFillColor(
    color[0],
    color[1],
    color[2]
  );
}

export function setPdfDrawColor(
  doc: jsPDF,
  color: readonly [
    number,
    number,
    number,
  ]
) {
  doc.setDrawColor(
    color[0],
    color[1],
    color[2]
  );
}

export function addPdfSectionHeading(
  doc: jsPDF,
  title: string,
  yPosition: number
) {
  doc.setFont(
    "helvetica",
    "bold"
  );

  doc.setFontSize(15);

  setPdfTextColor(
    doc,
    PDF_COLORS.heading
  );

  doc.text(
    title,
    PDF_LEFT_MARGIN,
    yPosition
  );

  setPdfDrawColor(
    doc,
    PDF_COLORS.primary
  );

  doc.setLineWidth(0.8);

  doc.line(
    PDF_LEFT_MARGIN,
    yPosition + 3,
    PDF_PAGE_WIDTH -
      PDF_RIGHT_MARGIN,
    yPosition + 3
  );

  return yPosition + 10;
}

export function addPdfPageHeader(
  doc: jsPDF,
  projectName: string
) {
  setPdfFillColor(
    doc,
    PDF_COLORS.primary
  );

  doc.rect(
    0,
    0,
    PDF_PAGE_WIDTH,
    30,
    "F"
  );

  doc.setFont(
    "helvetica",
    "bold"
  );

  doc.setFontSize(19);

  setPdfTextColor(
    doc,
    PDF_COLORS.white
  );

  doc.text(
    "JobClokr",
    PDF_LEFT_MARGIN,
    13
  );

  doc.setFont(
    "helvetica",
    "normal"
  );

  doc.setFontSize(9);

  doc.text(
    "Project Report",
    PDF_LEFT_MARGIN,
    21
  );

  doc.setFont(
    "helvetica",
    "bold"
  );

  doc.setFontSize(11);

  const projectNameLines =
    doc.splitTextToSize(
      projectName,
      85
    );

  doc.text(
    projectNameLines,
    PDF_PAGE_WIDTH -
      PDF_RIGHT_MARGIN,
    12,
    {
      align: "right",
    }
  );

  setPdfTextColor(
    doc,
    PDF_COLORS.heading
  );
}

export function addPdfPageFooter(
  doc: jsPDF,
  pageNumber: number,
  totalPages: number
) {
  setPdfDrawColor(
    doc,
    PDF_COLORS.border
  );

  doc.setLineWidth(0.3);

  doc.line(
    PDF_LEFT_MARGIN,
    PDF_PAGE_HEIGHT - 15,
    PDF_PAGE_WIDTH -
      PDF_RIGHT_MARGIN,
    PDF_PAGE_HEIGHT - 15
  );

  doc.setFont(
    "helvetica",
    "normal"
  );

  doc.setFontSize(8);

  setPdfTextColor(
    doc,
    PDF_COLORS.muted
  );

  doc.text(
    "Generated by JobClokr",
    PDF_LEFT_MARGIN,
    PDF_PAGE_HEIGHT - 9
  );

  doc.text(
    `Page ${pageNumber} of ${totalPages}`,
    PDF_PAGE_WIDTH -
      PDF_RIGHT_MARGIN,
    PDF_PAGE_HEIGHT - 9,
    {
      align: "right",
    }
  );

  setPdfTextColor(
    doc,
    PDF_COLORS.heading
  );
}

export function ensurePdfPageSpace(
  doc: jsPDF,
  yPosition: number,
  requiredHeight: number,
  projectName: string
) {
  if (
    yPosition +
      requiredHeight <=
    PDF_PAGE_HEIGHT -
      PDF_BOTTOM_MARGIN -
      7
  ) {
    return yPosition;
  }

  doc.addPage();

  addPdfPageHeader(
    doc,
    projectName
  );

  return 42;
}

export function formatPdfDate(
  dateValue?: string | null
) {
  if (!dateValue) {
    return "Not set";
  }

  const date =
    new Date(dateValue);

  if (
    Number.isNaN(
      date.getTime()
    )
  ) {
    return dateValue;
  }

  return date.toLocaleDateString(
    [],
    {
      month: "short",
      day: "numeric",
      year: "numeric",
    }
  );
}

export function formatPdfDateTime(
  dateValue: string
) {
  const date =
    new Date(dateValue);

  if (
    Number.isNaN(
      date.getTime()
    )
  ) {
    return "Date unavailable";
  }

  return date.toLocaleString(
    [],
    {
      month: "short",
      day: "numeric",
      year: "numeric",
      hour: "numeric",
      minute: "2-digit",
    }
  );
}

export function sanitizePdfFileName(
  value: string
) {
  return value
    .trim()
    .replace(
      /[<>:"/\\|?*]+/g,
      ""
    )
    .replace(
      /\s+/g,
      "-"
    )
    .toLowerCase();
}